name: spideranatomy
channels:
  - numba
  - simpleitk
  - conda-forge
  - defaults
dependencies:
  - python==3.7.0
  - dask==2022.02.0
  - distributed==2022.02.0
  - cloudpickle==2.2.0
  - numpy==1.21.6
  - scipy
  - scikit-image
  - scikit-learn
  - toolz==0.12.0
  - tornado
  - simpleitk
  - vedo
  - vispy
  - pyopengl
  - ipyvolume
  - pandas==1.3.5
  - lz4==3.1.3
  - numba
  - tqdm
  - pip
  - pip:
      - pynrrd
      - ome-zarr
      - git+https://github.com/pgzip/pgzip.git
