# mamba env create -f /mnt/c/Users/acorver/Documents/repositories/spider-anatomy/environment_workers.yml
name: spideranatomy_workers
channels:
  - numba
  - simpleitk
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - dask==2022.*
  - distributed==2022.*
  - numpy
  - spyder
  - vispy==0.6
  - pyopengl
  - natsort
  - tifffile
  - pyqtgraph
  - opencv
  - cython
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - graph-tool
  - pytorch
  - lz4==3.1.3
  - nt
  - tqdm
  - pip

